#ifndef CNUMKIT_H
#define CNUMKIT_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * CNUMKIT_EXPORT MACRO EXPLANATION
 * --------------------------------
 * This macro is automatically generated by CMake (GenerateExportHeader) and 
 * handles the complex symbol visibility rules across different platforms.
 * 
 * - On Windows (MSVC/MinGW), building a shared library (.dll) requires explicitly 
 *   telling the compiler which functions to export using __declspec(dllexport).
 *   When users consume the library, they need __declspec(dllimport).
 * - On Linux/macOS (GCC/Clang), it uses __attribute__((visibility("default"))) 
 *   to ensure only marked functions are exposed when compiling with -fvisibility=hidden.
 * 
 * This ensures our library behaves like a "real" professional library,
 * avoiding namespace pollution and working flawlessly across OSes as a shared object.
 */
#include "cnumkit_export.h"

#include "cnumkit/vector.h"
#include "cnumkit/matrix.h"
#include "cnumkit/linalg.h"
#include "cnumkit/optim.h"
#include "cnumkit/ml.h"
#include "cnumkit/error.h"
#include "cnumkit/contracts.h"

#ifdef __cplusplus
}
#endif

#endif /* CNUMKIT_H */
